<link rel="stylesheet" href="style.css">
<body>
<p>This page is supposed to be about me so here we go. Born 1998. Graduated High School in 2016. Computer science education
major. Supposed to graduate in Fall 2020. I plan on teaching in Muscogee County until I can move out with my girlfriend.
That's about it. Here's the profile picture I use for everything because it is so ridiculous. </p>


<a href= "/images/SakuraMeme.jpg"><img src="/images/SakuraMeme.jpg" width="624" height="468" title="Profile Picture of Sakura" alt="Sakura Kasugano from Street Fighter" />

</body>