<link rel="stylesheet" href="style.css">
<body>
<p>[Insert Contact Info here]<br>
Phone: (555) 555-5555 <br>
Email: "firstname@lastname.com"</p>

<img src="/images/KonoDioDa.JPG" width="400" height="400" title="You thought there would be text here, but it was me Dio!"  alt="JJBA Dio Meme"/>

<p>Taniks has no House. He kneels before no banner, owes allegiance to no Kell. He is a murderer, and very good at what he does.

I have been tracking him since Wolves broke their chains, yes? Now Taniks works for Wolf pack…but not for long.</p>

</body>