<link rel="stylesheet" href="style.css">

<img src="/images/Controllers.jpg" width="500" height="500" title="Video Game controllers" alt="Pile of controllers" />

<p>Video games are a commonality today but originally started as programs to test hardware.
It wasn't until 1963 that video games became popular. Their peak was during the 1980's where arcade
cabinets were the most common but it changed in 1983.</p>

<p> The industry crashed in 1983 because of games being poorly developed, PC gaming becoming dominant, and lack of faith.
Nintendo resurrected the industry by using the Nintendo Entertainment System and the Robotic Operating Buddy to say that it was a
toy not a game. Consumers did not pick up on it but with the release of games like Super Mario Brothers and The Legend of Zelda in
1984 the industry was up and running. Eventually as hardware and revenue increased competitors came in, such as Sega with their
mascot Sonic the Hedgehog. By this time in the early 1990's every genre of video game had a game to call their ancestor.
Platformers had Super Mario, Adventure games had The Legend of Zelda, Shooters had Doom and 2D Fighters had Street Fighter II to name
off a few genres.</p>